name: Deploy to Cloud Foundry

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cf CLI
        run: |
          wget -q -O cf.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf.deb
          rm cf.deb

      - name: Log in to Cloud Foundry
        run: cf login  -a 'https://api.cf.ap21.hana.ondemand.com/' -u 'nguyenda.gpt@gmail.com' -p '123123Qq.'

      - name: Deploy to Cloud Foundry
        uses: jhunt/cf-push@v1
        with:
          validate: false
